apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zqjzwvyiw-go 
  janus-idp.io/tekton: zqjzwvyiw-go
  backstage.io/kubernetes-id: zqjzwvyiw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zqjzwvyiw-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  